[package]
name = "fuels"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.61.*"

[dependencies]
flutter_rust_bridge = "1.61.*"
fuels = "0.32"
fuel-crypto = { version = "0.6", features = ["random"] }
fuels-signers = "0.32.2"
fuel-tx = "0.23"
futures = "0.3"
tokio = { version = "1.14.0", features = ["rt-multi-thread"] }
rand = { version = "0.8.4", default-features = false }